### ISSUE TITLE
no css file within package

### ISSUE THREAD

**Issue by Quentigus** [stephenhutchings/microns#2]
Hello,
I've used `npm` to install microns, but downloaded package doesn't include css files.

![image](https://user-images.githubusercontent.com/5646533/70333088-21f80800-1843-11ea-9ef6-3d46e4bebdbe.png)

Thanks in advance,

**Comment by stephenhutchings** [comment]
Hi @Quentigus ,
The package file was misconfigured and wasn't including the CSS. I've fixed this in b5263c1.
Thanks for posting the issue.
