### ISSUE TITLE
New icon suggestions

### ISSUE THREAD

**Issue by stephenhutchings** [stephenhutchings/microns#21]
This issue is here to collect suggestions and votes for new icons.

Please add your suggestions here instead of opening a new issue. If there is significant support for a specific suggestion, it will be moved to a separate issue.

**Comment by stephenhutchings** [comment]
This issue will remain closed while changes are discussed. Please still add your own suggestions or comments if you have them.

**Comment by vixalien** [comment]
I find there is a lack of money-related icons. I don't have an icon that can represent an action such as "pay". relevant candidates include the cash sign, dollar sign, or bank icon

**Comment by CalmArms** [comment]
Similarly to @vixalien but broadening their suggestion to "commerce" it could be ideal to have things like "cart", "bag", or "basket" for purchasing flows, and perhaps a "parcel" and "truck" for delivery related flows.

Adore this library of icons by the way, so well executed, thanks for creating them @stephenhutchings!

**Comment by v-ein** [comment]
Hello - I've noticed that in the audio/video section, there's no "Stop" icon. While it could probably be replaced with `mu-box-full`, that icon is a little bit larger than `mu-play` and other audio/video controls.

Other than that, an awesome icon library, clear and concise. And I especially like the "Details" section explaining all the how's and why's!

**Comment by omascia** [comment]
Along those icons about text formatting, like bold, italic, strikeout, I miss one to represent 'mark', marking text like with one of those colored pens. You know want I mean, I am not sure of the right word for this action in english.

**Comment by vixalien** [comment]
omascia, I think you mean 'highlighted'

**Comment by vaskark** [comment]
This is a beautiful set. I'd love it if there were battery, temperature, cpu, memory, etc, icons for better use with apps like polybar and lemonbar.

Otherwise, keep up the great work!

**Comment by win93** [comment]
There's an icon for bulleted list called "chapters". it would be great if there was also a numbered list icon

**Comment by PaulCEllsworth** [comment]
Seems like a simple one, but something looking a bit like a newspaper or open book? Could be used for either or have a set if somehow someone wanted something different for blog, ebook, news, etc.?

**Comment by MartijnOud** [comment]
An 'accessibility settings' icon would fit in great :)

**Comment by stephenhutchings** [comment]
The latest version ([1.2.0](https://github.com/stephenhutchings/microns/releases/tag/v1.2.0)) includes a handful of new icons.

- Shopping bag `mu-bag`
- Accessibility `mu-a11y`
- Dark mode `mu-mode-dark`
- Light mode `mu-mode-dark`
- Default mode `mu-mode-auto`
