### ISSUE TITLE
License of css

### ISSUE THREAD

**Issue by deemp** [stephenhutchings/microns#23]
Hi, @stephenhutchings! In https://github.com/deemp/purescript-css-frameworks,  I collect `.css` files and generate class names for PureScript. I'd like to include the [microns.css](https://github.com/stephenhutchings/microns/blob/master/fonts/microns.css) file there. Is it possible? What type of license should I write?

**Comment by stephenhutchings** [comment]
Please feel free to include the CSS in your project. The microns images are distributed under [CC BY-SA](http://creativecommons.org/licenses/by-sa/3.0/) licence.
