### ISSUE TITLE
Previous and Next have same code as Play and Pause

### ISSUE THREAD

**Issue by my1e5** [stephenhutchings/microns#24]
https://github.com/stephenhutchings/microns/blob/2d68ae57e4c9938e27ee3f8c9600476c49571dc1/icons.json#L215

This is on the cheat sheet as well. 

![image](https://github.com/stephenhutchings/microns/assets/10064103/b1dadf23-4b76-4a04-89d8-9bb8049ce411)

Inspecting the font file, they should be `E774` and `E775` ?

**Comment by stephenhutchings** [comment]
Thanks for raising this @my1e5. I will have a look ASAP.

**Comment by stephenhutchings** [comment]
I've added a check to prevent the dictionary getting out of sync again, which caught a few other mismatches too. Thanks again @my1e5 for logging this issue.
