### ISSUE TITLE
Can't find the ttf

### ISSUE THREAD

**Issue by ehgoodenough** [stephenhutchings/microns#3]
The current v1.0.5 version is missing `fonts/microns.ttf`. I see it in master, but it isn't in the published npm module.

My webpack loader, which tries to pull in each asset referenced in the css, is successfully pulling in the eot, woff2, woff and svg. But it is throwing an error when it can't find the ttf.

**Comment by stephenhutchings** [comment]
Thanks @ehgoodenough I've just merged and published to NPM. Thanks for taking the time to make a pull request!
